### ISSUE TITLE
Fix MongoDB

### ISSUE THREAD

**Issue by gesundkrank** [anycook/anycook-api#9]
After upgrading MongoDB to latest version an exception is thrown when trying to access recipe drafts: 
```
00:48:19.422 [http-nio-8080-exec-8] ERROR de.anycook.api.DraftApi - java.lang.ClassCastException: org.bson.BsonUndefined cannot be cast to java.lang.String
java.lang.ClassCastException: org.bson.BsonUndefined cannot be cast to java.lang.String
        at de.anycook.drafts.RecipeDraft.read(RecipeDraft.java:166) ~[classes/:?]
        at de.anycook.drafts.RecipeDraft.<init>(RecipeDraft.java:47) ~[classes/:?]
        at de.anycook.db.drafts.mongo.MongoDBRecipeDraftsStore.getDrafts(MongoDBRecipeDraftsStore.java:84) ~[classes/:?]
        at de.anycook.api.DraftApi.get(DraftApi.java:69) [classes/:?]
...
```

**Comment by gesundkrank** [comment]
Works again.
